### ISSUE TITLE
Vaccines route returning http code 502 

### ISSUE THREAD

**Issue by Gustavo-Cauzzi** [M-Media-Group/Covid-19-API#19] opened 2021-05-11 22:33 UTC
![image](https://user-images.githubusercontent.com/66269430/117892596-620cb700-b28f-11eb-8ddc-26229998f248.png)

The route is returning this error with the status code of 502. Any idea why this is happening?

**Comment by yano404** [comment] 2021-05-12 03:28
Maybe because the [data source](https://github.com/govex/COVID-19) CSV format has changed at [this  commit](https://github.com/govex/COVID-19/commit/6519ee7d74980effafb3940e52da1b7174a68381#diff-9df7815a85d16a04c74f0cb61eb810c3541f2fe1303364348b5197362b642c9a).
I think.

**Comment by mwargan** [comment] 2021-05-12 09:06
Indeed, issue caused by change in data source. Looking into it now, pull requests welcome :)

**Comment by mwargan** [comment] 2021-05-12 09:33
Thanks everyone for reporting. Should be fixed with https://github.com/M-Media-Group/Covid-19-API/commit/4011fc572c913f85c32acfad92138174cf4f05b1 - issue caused because vaccine data provider switched from "0" values to blank values.

**Closed as completed by mwargan** 2021-05-12 09:33 UTC
